/**
 * The workshop's bookkeeping: routing, staleness, and the storyboard importer.
 *
 * The behaviours guarded here are the ones that fail quietly. A `.mp3` filed
 * under the wrong section is generated by the wrong model; an asset that has
 * gone stale looks finished; a prompt edited through the UI can take a file's
 * comments with it. None of those announce themselves.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ScenarioSchema } from '../src/scenario/schema.ts';
import { assetReferencesOf, assetsOf, parseScenarioSource } from '../src/scenario/load.ts';
import {
  ProjectSchema,
  recipeHash,
  resolveRecipe,
  pathsOf,
  EMPTY_LEDGER,
  LedgerSchema,
} from '../tools/editor/project.ts';
import { buildOverview } from '../tools/editor/sections.ts';
import { wireVoiceInto } from '../tools/editor/wire.ts';
import { migrateShotsInto } from '../tools/editor/shots.ts';
import { parseStoryboard, proposeAssets, seedRowsFor } from '../tools/editor/storyboard.ts';
import { scaffoldFromStoryboard } from '../tools/editor/scaffold.ts';

function scenario(overrides: Record<string, unknown> = {}) {
  return ScenarioSchema.parse({
    id: 'x',
    title: 'X',
    start: 'a',
    characters: { ada: { name: 'Ada', sprite: 'ada.png' } },
    scenes: {
      room: {
        background: 'room.jpg',
        video: 'room.mp4',
        music: 'pad.mp3',
        ambience: 'hum.mp3',
      },
    },
    nodes: [
      {
        id: 'a',
        type: 'dialogue',
        scene: 'room',
        lines: [{ who: 'ada', text: 'Hello', voice: 'ada-a-01.mp3', sfx: 'door.mp3' }],
        next: 'z',
      },
      { id: 'z', type: 'end' },
    ],
    ...overrides,
  });
}

describe('asset routing', () => {
  test('sections come from the schema field, not the file extension', () => {
    const refs = assetReferencesOf(scenario());
    const section = (file: string) => refs.find((r) => r.file === file)?.section;

    // Four .mp3 files, four different kinds of work.
    assert.equal(section('pad.mp3'), 'music');
    assert.equal(section('hum.mp3'), 'ambience');
    assert.equal(section('ada-a-01.mp3'), 'voice');
    assert.equal(section('door.mp3'), 'sfx');

    assert.equal(section('room.jpg'), 'images');
    assert.equal(section('ada.png'), 'images');
    assert.equal(section('room.mp4'), 'video');
  });

  test('every reference records where it came from', () => {
    const refs = assetReferencesOf(scenario());
    assert.deepEqual(
      refs.find((r) => r.file === 'ada-a-01.mp3')?.origin,
      { kind: 'voice', node: 'a', line: 0 },
    );
    assert.deepEqual(
      refs.find((r) => r.file === 'ada.png')?.origin,
      { kind: 'sprite', character: 'ada' },
    );
  });

  test('assetsOf still dedupes and sorts', () => {
    const shared = scenario({
      scenes: { one: { ambience: 'wind.mp3' }, two: { ambience: 'wind.mp3' } },
    });
    const files = assetsOf(shared);
    assert.equal(files.filter((f) => f === 'wind.mp3').length, 1);
    assert.deepEqual([...files].sort(), files);
  });
});

describe('recipe hashing', () => {
  const project = ProjectSchema.parse({
    project: 'p',
    scenario: 'scenario.yaml',
    publish: 'dist/assets',
    sections: { images: { style: 'painterly', negative: 'text' } },
    assets: { 'room.jpg': { prompt: 'a room', params: { steps: 28, cfg: 3.5 } } },
  });

  test('section style is folded in, so editing it restages the whole section', () => {
    const before = recipeHash(resolveRecipe(project, 'images', 'room.jpg'));
    const after = recipeHash(
      resolveRecipe(
        { ...project, sections: { images: { ...project.sections.images!, style: 'photoreal' } } },
        'images',
        'room.jpg',
      ),
    );
    assert.notEqual(before, after);
  });

  test('key order is not part of the recipe', () => {
    const a = recipeHash(resolveRecipe(project, 'images', 'room.jpg'));
    const reordered = ProjectSchema.parse({
      project: 'p',
      scenario: 'scenario.yaml',
      publish: 'dist/assets',
      sections: { images: { negative: 'text', style: 'painterly' } },
      assets: { 'room.jpg': { params: { cfg: 3.5, steps: 28 }, prompt: 'a room' } },
    });
    assert.equal(a, recipeHash(resolveRecipe(reordered, 'images', 'room.jpg')));
  });

  test('row params override section defaults', () => {
    const withDefaults = ProjectSchema.parse({
      project: 'p',
      scenario: 'scenario.yaml',
      publish: 'dist/assets',
      sections: { images: { defaults: { steps: 20 } } },
      assets: { 'room.jpg': { params: { steps: 28 } } },
    });
    assert.equal(resolveRecipe(withDefaults, 'images', 'room.jpg').params.steps, 28);
  });
});

describe('the status board', () => {
  let dir: string;

  function projectAt(assets: Record<string, unknown> = {}) {
    return ProjectSchema.parse({
      project: 'p',
      scenario: 'scenario.yaml',
      publish: 'dist/assets',
      generated: 'generated',
      assets,
    });
  }

  async function overviewOf(
    project: ReturnType<typeof projectAt>,
    ledger = structuredClone(EMPTY_LEDGER),
  ) {
    const paths = pathsOf(join(dir, 'project.yaml'), project);
    return buildOverview(scenario(), project, ledger, paths);
  }

  function find(overview: Awaited<ReturnType<typeof overviewOf>>, file: string) {
    for (const section of overview.sections) {
      const hit = section.assets.find((a) => a.file === file);
      if (hit) return hit;
    }
    throw new Error(`${file} not in any section`);
  }

  test('an asset with no takes and no published file is missing', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      const overview = await overviewOf(projectAt());
      assert.equal(find(overview, 'room.jpg').status, 'missing');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('a file dropped into the publish folder reads as unmanaged, not done', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      mkdirSync(join(dir, 'dist', 'assets'), { recursive: true });
      writeFileSync(join(dir, 'dist', 'assets', 'room.jpg'), 'x');
      const overview = await overviewOf(projectAt());
      assert.equal(find(overview, 'room.jpg').status, 'unmanaged');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('takes with nothing selected are unselected', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      mkdirSync(join(dir, 'generated', 'images', 'room.jpg'), { recursive: true });
      writeFileSync(join(dir, 'generated', 'images', 'room.jpg', '0001.png'), 'x');
      const overview = await overviewOf(projectAt());
      const view = find(overview, 'room.jpg');
      assert.equal(view.status, 'unselected');
      assert.equal(view.takes.length, 1);
      assert.equal(view.takes[0]!.untracked, true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('a selected take whose recipe has since changed is stale', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      mkdirSync(join(dir, 'generated', 'images', 'room.jpg'), { recursive: true });
      writeFileSync(join(dir, 'generated', 'images', 'room.jpg', '0001.png'), 'x');

      const project = projectAt({ 'room.jpg': { prompt: 'the new prompt' } });
      const ledger = LedgerSchema.parse({
        assets: {
          'room.jpg': {
            selected: '0001.png',
            takes: [{ id: '0001.png', hash: 'made-under-the-old-prompt', at: 'then' }],
          },
        },
      });
      assert.equal(find(await overviewOf(project, ledger), 'room.jpg').status, 'stale');

      // The same take, recorded under the recipe that is actually in force.
      const current = recipeHash(resolveRecipe(project, 'images', 'room.jpg'));
      const fresh = LedgerSchema.parse({
        assets: {
          'room.jpg': {
            selected: '0001.png',
            takes: [{ id: '0001.png', hash: current, at: 'now' }],
          },
        },
      });
      assert.equal(find(await overviewOf(project, fresh), 'room.jpg').status, 'ready');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('a frozen asset never reports stale', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      mkdirSync(join(dir, 'generated', 'images', 'room.jpg'), { recursive: true });
      writeFileSync(join(dir, 'generated', 'images', 'room.jpg', '0001.png'), 'x');
      const project = projectAt({ 'room.jpg': { prompt: 'changed', freeze: true } });
      const ledger = LedgerSchema.parse({
        assets: {
          'room.jpg': {
            selected: '0001.png',
            takes: [{ id: '0001.png', hash: 'stale-by-any-other-measure', at: 'then' }],
          },
        },
      });
      const view = find(await overviewOf(project, ledger), 'room.jpg');
      assert.equal(view.status, 'ready');
      assert.equal(view.frozen, true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('a recipe the scenario no longer references is reported as an orphan', async () => {
    dir = mkdtempSync(join(tmpdir(), 'is-project-'));
    try {
      const overview = await overviewOf(projectAt({ 'deleted-shot.jpg': { prompt: 'gone' } }));
      assert.deepEqual(overview.orphans, ['deleted-shot.jpg']);
      assert.match(overview.problems.map((p) => p.message).join('\n'), /deleted-shot\.jpg/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('the storyboard importer', () => {
  const SOURCE = `
## ACT A — HALIFAX

### Shot A.1 — Cold open, the jetty
**Hold:** 8 s · **Scene:** \`halifax\`

**IMAGE**
\`\`\`
STYLE. Pre-dawn at a working naval jetty, wet concrete reflecting sodium light.
NEGATIVE.
\`\`\`
**MOTION** Slow parallax push toward the bow; mist drifts left to right.

**VO — \`narr\`**
> Zero four hundred, Halifax.
> The pier is busy the way it always is.

*Delivery: unhurried, matter-of-fact.*

### Shot D.5 — The link dies
**Hold:** 4 s · **Scene:** \`control_cell\`

**IMAGE**
\`\`\`
STYLE. A console going dark.
\`\`\`

**SFX** One hard transient, then ringing air.

**DIALOGUE**

\`tran\`:
> We've lost the link.

\`beau\`:
> Say again?
`;

  test('shots, holds, scenes and fenced prompts survive the round trip', () => {
    const { shots } = parseStoryboard(SOURCE);
    assert.equal(shots.length, 2);

    const [first, second] = shots;
    assert.equal(first!.id, 'A.1');
    assert.equal(first!.title, 'Cold open, the jetty');
    assert.equal(first!.hold, 8);
    assert.equal(first!.scene, 'halifax');
    assert.match(first!.image!, /wet concrete/);
    assert.match(first!.motion!, /parallax/);
    assert.equal(second!.sfx, 'One hard transient, then ringing air.');
  });

  test('a VO block and a DIALOGUE block both produce attributed lines', () => {
    const { shots } = parseStoryboard(SOURCE);
    assert.deepEqual(
      shots[0]!.lines.map((l) => l.who),
      ['narr'],
    );
    assert.match(shots[0]!.lines[0]!.text, /Zero four hundred/);
    assert.equal(shots[0]!.lines[0]!.delivery, 'unhurried, matter-of-fact.');
    assert.deepEqual(
      shots[1]!.lines.map((l) => l.who),
      ['tran', 'beau'],
    );
  });

  test('a delivery note that wraps onto a second line is still read', () => {
    // The longest and most useful notes are exactly the ones that do not fit on
    // one line. Reading only the first line dropped four of the nine notes in
    // the real storyboard without saying a word about it.
    const wrapped = `
### Shot E.2 — The convergence
**Hold:** 12 s · **Scene:** \`station\` · **Node:** \`e_tree\`

**VO — \`narr\`**
> It does not matter what the room voted.

*Delivery: this is the thesis line. Slow it down. Let the silence after "weeks
ago" run a full beat before the last sentence.*

---
`;
    const { shots, warnings } = parseStoryboard(wrapped);
    assert.equal(
      shots[0]!.lines[0]!.delivery,
      'this is the thesis line. Slow it down. Let the silence after "weeks ago" run a full ' +
        'beat before the last sentence.',
    );
    assert.deepEqual(
      warnings.filter((w) => w.includes('Delivery')),
      [],
    );
  });

  test('an ending is a beat, and a numbered section is furniture', () => {
    const tail = `
### ENDING A — \`end_strike\`
**Hold:** 14 s · **Scene:** \`standoff\` · **Node:** \`end_strike\`

**IMAGE**
\`\`\`
STYLE. Two vessels on black water, the first launch plume rising.
\`\`\`

### DEBRIEF END NODE — \`debrief\` *(both endings route here)*
**Scene:** \`debrief\` · **Node:** \`debrief\`

**IMAGE**
\`\`\`
STYLE. The empty control cell, screens dark.
\`\`\`

## 5. Production checklist

### 3.1 The style token
### Media fields
`;
    // Before this, an ending was skipped in silence: not imported, not
    // reported, on no list anywhere. The `###` headings that are document
    // furniture still have to stay furniture, or the board fills with prose.
    const { shots } = parseStoryboard(tail);
    assert.deepEqual(
      shots.map((s) => s.id),
      ['ENDING A', 'DEBRIEF END NODE'],
    );
    assert.equal(shots[0]!.node, 'end_strike');
    assert.match(shots[1]!.image!, /empty control cell/);
  });

  test('a shot names its node when the id convention cannot carry it', () => {
    const stated = `
### Shot E.1a — if \`defend\` won
**Hold:** 8 s · **Scene:** \`station\` · **Node:** \`p1_defend\`

**DIALOGUE**

\`narr\`:
> The room says: shoot.
`;
    // `p1_defend` is named for the poll result, so no prefix of it will ever
    // reach E.1a. Said out loud, it maps; left unsaid, it never could.
    assert.equal(parseStoryboard(stated).shots[0]!.node, 'p1_defend');
  });

  test('voice filenames follow the storyboard s own convention', () => {
    const { shots } = parseStoryboard(SOURCE);
    const files = proposeAssets(shots).map((a) => a.file);
    // The storyboard documents `tran-d5-01.mp3` by hand; the importer must
    // produce exactly that, under the folder its media type is filed in.
    assert.ok(files.includes('voice/tran-d5-01.mp3'), files.join(', '));
    assert.ok(files.includes('voice/narr-a1-01.mp3'));
    // The one place in the pipeline allowed to invent a filename is also the
    // one place that writes the scenario referencing it, so the folder goes in
    // here rather than being sorted on afterwards.
    assert.ok(files.includes('images/halifax-a1.jpg'), files.join(', '));
  });

  test('scaffolding gives a second shot in one place its own picture', () => {
    const twoShotsOneScene = SOURCE.replace('`control_cell`', '`halifax`');
    const { scenarioYaml, report } = scaffoldFromStoryboard(twoShotsOneScene, {
      id: 'demo',
      title: 'Demo',
    });

    const parsed = parseScenarioSource(scenarioYaml);
    assert.equal(parsed.ok, true, JSON.stringify(parsed));
    if (!parsed.ok) return;

    // Both shots play in `halifax`. The first is the establishing shot and its
    // still stays on the scene; the second carries its own on its node. A
    // second scene for the second camera setup would restart the room's
    // ambience halfway through the act.
    assert.equal(Object.keys(parsed.scenario.scenes).length, 1);
    const [first, second] = parsed.scenario.nodes;
    assert.equal(first!.background, undefined);
    assert.equal(parsed.scenario.scenes.halifax!.background, 'images/halifax-a1.jpg');
    assert.equal(second!.background, 'images/halifax-d5.jpg');

    // And nothing the storyboard wrote is left with nowhere to go.
    const stills = report.unplaceable.filter(
      (entry) => entry.section === 'images' || entry.section === 'video',
    );
    assert.deepEqual(stills, []);
  });
});

describe('giving every shot its own picture', () => {
  // Three beats, two of them in one room. `halifax_flank` is the shape an
  // author reaches for when only a scene can hold a background: a second
  // camera setup wearing a scene's clothes.
  const STORYBOARD = [
    '## ACT A',
    '',
    '### Shot A.1 — The jetty',
    '**Hold:** 8 s · **Scene:** \`halifax\`',
    '',
    '**IMAGE**',
    '\`\`\`',
    'STYLE. The jetty before dawn.',
    '\`\`\`',
    '**MOTION** Slow push toward the bow.',
    '',
    '### Shot A.2 — The absence',
    '**Hold:** 7 s · **Scene:** \`halifax\`',
    '',
    '**IMAGE**',
    '\`\`\`',
    'STYLE. No gangway, no brow, nothing to walk up.',
    '\`\`\`',
    '',
    '### Shot A.3 — Departure',
    '**Hold:** 6 s · **Scene:** \`halifax\`',
    '',
    '**IMAGE**',
    '\`\`\`',
    'STYLE. The hull pulling away into open water.',
    '\`\`\`',
    '**MOTION** The wake widens.',
    '',
  ].join('\n');

  function source(flankAmbience = 'harbour.mp3'): string {
    return [
      'id: demo',
      'title: Demo',
      'start: a1_jetty',
      'characters:',
      '  narr: { name: Narr }',
      'scenes:',
      '  # The sibling below exists purely to carry a second camera setup.',
      '  halifax: { background: a1.jpg, video: a1.mp4, ambience: harbour.mp3 }',
      `  halifax_flank: { background: a2-flank.jpg, ambience: ${flankAmbience} }`,
      'nodes:',
      '  - id: a1_jetty',
      '    type: dialogue',
      '    scene: halifax',
      '    lines:',
      '      - who: narr',
      '        text: >-',
      '          A hand-wrapped folded scalar',
      '          that must survive untouched.',
      '        hold: 8',
      '    next: a2_absence',
      '',
      '  # Why this beat is seven seconds and not five.',
      '  - id: a2_absence',
      '    type: dialogue',
      '    scene: halifax_flank',
      '    lines:',
      '      - { who: narr, text: There is no brow., hold: 7 }',
      '    next: a3_departure',
      '',
      '  - id: a3_departure',
      '    type: dialogue',
      '    scene: halifax',
      '    lines:',
      '      - who: narr',
      '        text: No one waves it off.',
      '        hold: 6',
      '    next: fin',
      '',
      '  - id: fin',
      '    type: end',
      '    text: Done',
      '',
    ].join('\n');
  }

  function migrate(text: string) {
    const parsed = parseScenarioSource(text);
    assert.equal(parsed.ok, true, JSON.stringify(parsed));
    if (!parsed.ok) throw new Error('unreachable');
    return migrateShotsInto(text, parsed.scenario, parseStoryboard(STORYBOARD).shots);
  }

  test('the establishing shot keeps the scene, later shots get their own', () => {
    const result = migrate(source());
    const parsed = parseScenarioSource(result.source);
    assert.equal(parsed.ok, true, JSON.stringify(parsed));
    if (!parsed.ok) return;

    const byId = new Map(parsed.scenario.nodes.map((node) => [node.id, node]));

    // A.1 is what `halifax`'s background has always depicted, so it stays put.
    assert.equal(byId.get('a1_jetty')!.background, undefined);
    assert.equal(parsed.scenario.scenes.halifax!.background, 'a1.jpg');

    // A.3 has nowhere to hang until now. Named the way the pipeline names
    // anything it invents: under the folder its media type is filed in.
    assert.equal(byId.get('a3_departure')!.background, 'images/halifax-a3.jpg');
    assert.equal(byId.get('a3_departure')!.video, 'video/halifax-a3.mp4');
  });

  test('a stand-in scene folds back into the place the storyboard names', () => {
    const result = migrate(source());
    assert.deepEqual(
      result.folded.map((entry) => [entry.scene, entry.into, entry.nodes]),
      [['halifax_flank', 'halifax', ['a2_absence']]],
    );

    const parsed = parseScenarioSource(result.source);
    if (!parsed.ok) return assert.fail(JSON.stringify(parsed));
    const node = parsed.scenario.nodes.find((candidate) => candidate.id === 'a2_absence')!;
    assert.equal(node.scene, 'halifax');
    // The filename it already declared, unchanged. Renaming it would orphan
    // every prompt the author has written against it.
    assert.equal(node.background, 'a2-flank.jpg');
    // A.2 describes no motion, so nothing invents a clip for it.
    assert.equal(node.video, undefined);
    assert.equal('halifax_flank' in parsed.scenario.scenes, false);
  });

  test('folding is refused when it would change what the audience hears', () => {
    const result = migrate(source('engine-room.mp3'));
    assert.deepEqual(result.folded, []);
    assert.equal(result.skipped.length, 1);
    assert.match(result.skipped[0]!.why, /different music or ambience/);

    // And the scene it would not fold is still there, still referenced.
    const parsed = parseScenarioSource(result.source);
    if (!parsed.ok) return assert.fail(JSON.stringify(parsed));
    assert.equal('halifax_flank' in parsed.scenario.scenes, true);
  });

  test('running it a second time changes nothing', () => {
    const once = migrate(source());
    const twice = migrate(once.source);
    assert.equal(twice.source, once.source);
    assert.deepEqual(twice.moved, []);
    assert.deepEqual(twice.folded, []);
  });

  test('comments and hand-wrapped scalars survive the edit', () => {
    const result = migrate(source());
    assert.match(result.source, /# Why this beat is seven seconds and not five\./);
    assert.match(result.source, /text: >-\n          A hand-wrapped folded scalar\n/);
    // The flow-mapped line stays a flow map rather than being reserialised.
    assert.match(result.source, /- \{ who: narr, text: There is no brow\., hold: 7 \}/);
  });

  test('a comment describing the scenes it removed is reported, not rewritten', () => {
    const result = migrate(source());
    assert.equal(result.stale.length, 1);
    assert.match(result.stale[0]!.text, /second camera setup/);
    // Reported and left alone: the prose in a scenario belongs to its author.
    assert.match(result.source, /purely to carry a second camera setup/);
  });

  test('every storyboard prompt has somewhere to go afterwards', () => {
    const shots = parseStoryboard(STORYBOARD).shots;
    const before = parseScenarioSource(source());
    if (!before.ok) return assert.fail(JSON.stringify(before));

    const stillsWithNoHome = (scenario: typeof before.scenario) =>
      seedRowsFor(scenario, shots).unmatched.filter(
        (entry) => entry.kind === 'image' || entry.kind === 'video',
      );

    // A.3's still and clip have nowhere to hang — `halifax` already carries
    // A.1's picture — which is the whole reason this migration exists.
    assert.deepEqual(
      stillsWithNoHome(before.scenario).map((entry) => [entry.shot, entry.kind]),
      [
        ['A.3', 'image'],
        ['A.3', 'video'],
      ],
    );

    const after = parseScenarioSource(migrate(source()).source);
    if (!after.ok) return assert.fail(JSON.stringify(after));
    assert.deepEqual(stillsWithNoHome(after.scenario), []);
  });
});

describe('editing a recipe through the UI', () => {
  test('a field write keeps every comment in project.yaml', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-projects-'));
    try {
      const projectDir = join(root, 'demo');
      mkdirSync(projectDir, { recursive: true });

      writeFileSync(
        join(projectDir, 'scenario.yaml'),
        [
          'id: demo',
          'title: Demo',
          'start: a',
          'scenes:',
          '  room: { background: room.jpg }',
          'nodes:',
          '  - { id: a, type: dialogue, scene: room, lines: [{ text: Hi }], next: z }',
          '  - { id: z, type: end }',
          '',
        ].join('\n'),
        'utf8',
      );

      writeFileSync(
        join(projectDir, 'project.yaml'),
        [
          '# Why this project looks the way it does.',
          'project: demo',
          'scenario: scenario.yaml',
          'publish: dist/assets',
          'assets:',
          '  # The slate background is deliberate. Do not brighten it.',
          '  room.jpg:',
          '    prompt: a slate room',
          '',
        ].join('\n'),
        'utf8',
      );

      // The config location is read when the module is first evaluated, so the
      // import has to happen after the environment is set — and it points at a
      // throwaway folder so the real editor config is never touched.
      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { editAssetField } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      await editAssetField('demo', {
        file: 'room.jpg',
        field: 'notes',
        value: 'wants a warmer horizon',
      });

      const after = readFileSync(join(projectDir, 'project.yaml'), 'utf8');
      assert.match(after, /# Why this project looks the way it does\./);
      assert.match(after, /# The slate background is deliberate/);
      assert.match(after, /wants a warmer horizon/);
      // The prompt it was not asked to touch has to come through unchanged.
      assert.match(after, /prompt: a slate room/);
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('the workspace', () => {
  test('containment keeps a project name from walking out of the folder', async () => {
    const { within } = await import('../tools/editor/workspace.ts');
    assert.equal(within('/work', '/work/site'), true);
    assert.equal(within('/work', '/work'), true);
    // The prefix trap: /work/site must not count as being inside /work/si.
    assert.equal(within('/work/si', '/work/site'), false);
    assert.equal(within('/work', '/work/../elsewhere'), false);
  });

  test('a folder with only a scenario.yaml is already a project', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'moved-in');
      mkdirSync(dir, { recursive: true });
      writeFileSync(
        join(dir, 'scenario.yaml'),
        'id: x\ntitle: X\nstart: z\nnodes: [{ id: z, type: end }]\n',
        'utf8',
      );
      // A folder with no scenario is not a project and must not be listed.
      mkdirSync(join(root, 'just-a-folder'), { recursive: true });

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { listProjects, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const listed = await listProjects();
      assert.deepEqual(
        listed.map((p) => [p.name, p.hasProjectFile]),
        [['moved-in', false]],
      );

      // It opens, and says plainly that prompts have nowhere to go yet.
      const opened = await openProject('moved-in');
      assert.equal(opened.projectSource, undefined);
      assert.match(opened.problems.map((p) => p.message).join('\n'), /No project\.yaml yet/);
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('seeding keys rows to the filenames the scenario declares, never its own', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      writeFileSync(
        join(dir, 'demo-storyboard.md'),
        [
          '### Shot A.1 — Open',
          '**Hold:** 5 s · **Scene:** `room`',
          '',
          '**IMAGE**',
          '```',
          'the prompt the storyboard suggests',
          '```',
          '',
          '**VO — `narr`**',
          '> Hello there.',
          '',
        ].join('\n'),
        'utf8',
      );

      // The scenario names its files. Nothing here is called `room-a1.jpg`,
      // which is what the storyboard's own convention would have produced.
      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: a1_open',
          'characters: { narr: { name: Narr } }',
          'scenes:',
          '  room: { background: establishing-shot.jpg }',
          'nodes:',
          '  - id: a1_open',
          '    type: dialogue',
          '    scene: room',
          '    lines:',
          '      - { who: narr, text: Hello there., voice: narrator-open.mp3, hold: 3 }',
          '    next: z',
          '  - { id: z, type: end }',
          '',
        ].join('\n'),
        'utf8',
      );
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'storyboard: demo-storyboard.md',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { syncFromStoryboard, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const result = await syncFromStoryboard('demo');

      // The editor and the player have to agree on filenames: the player opens
      // exactly what scenario.yaml names, so a prompt written against anything
      // else would belong to a file nothing will ever load.
      assert.deepEqual(result.added, ['establishing-shot.jpg', 'narrator-open.mp3']);

      const after = readFileSync(join(dir, 'project.yaml'), 'utf8');
      assert.match(after, /the prompt the storyboard suggests/);
      assert.match(after, /Hello there\./);
      assert.doesNotMatch(after, /room-a1/);

      // And the proof: every seeded row is on the board, none orphaned.
      const opened = await openProject('demo');
      assert.deepEqual(opened.overview.orphans, []);
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('a tuned prompt survives re-seeding, and unmatched shots are reported', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      writeFileSync(
        join(dir, 'demo-storyboard.md'),
        [
          '### Shot A.1 — Open',
          '**Hold:** 5 s · **Scene:** `room`',
          '',
          '**IMAGE**',
          '```',
          'the prompt the storyboard suggests',
          '```',
          '',
          '**VO — `narr`**',
          '> Hello there.',
          '',
        ].join('\n'),
        'utf8',
      );
      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: a1_open',
          'scenes:',
          '  room: { background: establishing-shot.jpg }',
          'nodes:',
          '  - { id: a1_open, type: dialogue, scene: room, lines: [{ text: Hi }], next: z }',
          '  - { id: z, type: end }',
          '',
        ].join('\n'),
        'utf8',
      );
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'storyboard: demo-storyboard.md',
          'assets:',
          '  establishing-shot.jpg:',
          '    prompt: the version I spent an afternoon tuning',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { syncFromStoryboard } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const result = await syncFromStoryboard('demo');
      const after = readFileSync(join(dir, 'project.yaml'), 'utf8');

      assert.deepEqual(result.added, []);
      assert.match(after, /the version I spent an afternoon tuning/);
      assert.doesNotMatch(after, /the prompt the storyboard suggests/);

      // The storyboard has a spoken line; the scenario wires no voice file for
      // it. That is reported rather than invented into existence.
      assert.ok(
        result.unmatched.some((item) => item.shot === 'A.1' && item.kind === 'voice'),
        JSON.stringify(result.unmatched),
      );
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('a scene whose opening node was never storyboarded still finds its prompt', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      writeFileSync(
        join(dir, 'demo-storyboard.md'),
        [
          '### DEBRIEF END NODE — `debrief`',
          '**Scene:** `debrief` · **Node:** `debrief`',
          '',
          '**IMAGE**',
          '```',
          'the empty control cell, screens dark',
          '```',
          '',
        ].join('\n'),
        'utf8',
      );

      // `debrief` opens on the fiction notice, which no shot describes, and is
      // reused at the end by the shot that does. A scene has one background,
      // so the shot that plays there is describing it either way.
      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: fiction_notice',
          'scenes:',
          '  debrief: { background: debrief.jpg }',
          'nodes:',
          '  - id: fiction_notice',
          '    type: dialogue',
          '    scene: debrief',
          '    lines: [{ text: Everything here is invented., hold: 3 }]',
          '    next: debrief',
          '  - { id: debrief, type: end, scene: debrief, text: Who decided? }',
          '',
        ].join('\n'),
        'utf8',
      );
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'storyboard: demo-storyboard.md',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { syncFromStoryboard, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const result = await syncFromStoryboard('demo');
      const assets = (await openProject('demo')).project.assets;

      assert.deepEqual(result.added, ['debrief.jpg']);
      assert.equal(assets['debrief.jpg']?.prompt, 'the empty control cell, screens dark');
      assert.deepEqual(result.unmatched, []);
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('a stated node fills the hole it left, and never overwrites a tuned prompt', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      writeFileSync(
        join(dir, 'demo-storyboard.md'),
        [
          '### Shot E.1a — if `defend` won',
          '**Hold:** 8 s · **Scene:** `station` · **Node:** `p1_defend`',
          '',
          '**DIALOGUE**',
          '',
          '`narr`:',
          '> The room says: shoot.',
          '',
          '*Delivery: flat, no relish.*',
          '',
          '### Shot Z.9 — Nowhere',
          '**Hold:** 3 s · **Scene:** `station` · **Node:** `no_such_node`',
          '',
          '**IMAGE**',
          '```',
          'a prompt with nowhere to go',
          '```',
          '',
        ].join('\n'),
        'utf8',
      );

      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: p1_defend',
          'characters: { narr: { name: Narr }, pf: { name: PF } }',
          'scenes: { station: {} }',
          'nodes:',
          '  - id: p1_defend',
          '    type: dialogue',
          '    scene: station',
          '    lines:',
          '      - { who: narr, text: "The room says: shoot.", voice: narr-e1a-01.mp3, hold: 4 }',
          '      - { who: pf, text: Withholding., voice: pf-e1a-01.mp3, hold: 4 }',
          '    next: z',
          '  - { id: z, type: end }',
          '',
        ].join('\n'),
        'utf8',
      );

      // The state a mapping fix arrives into: rows already on the board, one of
      // them carrying a prompt somebody wrote by hand.
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'storyboard: demo-storyboard.md',
          'assets:',
          '  narr-e1a-01.mp3:',
          '    text: "The room says: shoot."',
          '  pf-e1a-01.mp3:',
          '    prompt: the version I spent an afternoon tuning',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { syncFromStoryboard, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const result = await syncFromStoryboard('demo');
      const assets = (await openProject('demo')).project.assets;

      // The note reaches the row that was already there, because an absent
      // field is a hole rather than a decision.
      assert.deepEqual(result.added, []);
      assert.deepEqual(result.filled, ['narr-e1a-01.mp3', 'pf-e1a-01.mp3']);
      assert.equal(assets['narr-e1a-01.mp3']?.prompt, 'flat, no relish.');
      assert.equal(assets['narr-e1a-01.mp3']?.source?.shot, 'E.1a');

      // The hand-written prompt stands. The fields around it that were never
      // written still get filled — filling a hole is not overwriting a choice.
      assert.equal(assets['pf-e1a-01.mp3']?.prompt, 'the version I spent an afternoon tuning');
      assert.equal(assets['pf-e1a-01.mp3']?.text, 'Withholding.');

      // A **Node:** that names nothing is a typo, and a typo that maps to
      // nothing silently is how a shot's prompts disappear for good.
      assert.ok(
        result.unmatched.some((item) => item.kind === 'node' && item.shot === 'Z.9'),
        JSON.stringify(result.unmatched),
      );
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('pruning removes recipes the scenario stopped referencing', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: a',
          'scenes: { room: { background: kept.jpg } }',
          'nodes:',
          '  - { id: a, type: end, scene: room }',
          '',
        ].join('\n'),
        'utf8',
      );

      // `renamed.jpg` is what a rename leaves behind: a recipe for a file the
      // scenario no longer asks for. Generating it would be GPU hours spent on
      // something nothing plays.
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          '# The author owns this file.',
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'assets:',
          '  kept.jpg:',
          '    prompt: still referenced',
          '  renamed.jpg:',
          '    prompt: left behind by a rename',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { pruneOrphans, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      const before = await openProject('demo');
      assert.deepEqual(before.overview.orphans, ['renamed.jpg']);

      const result = await pruneOrphans('demo');
      assert.deepEqual(result.removed, ['renamed.jpg']);

      const after = readFileSync(join(dir, 'project.yaml'), 'utf8');
      assert.doesNotMatch(after, /renamed\.jpg/);
      assert.match(after, /still referenced/);
      // Removing a row is still a surgical edit: the comments stay.
      assert.match(after, /# The author owns this file\./);
      assert.deepEqual((await openProject('demo')).overview.orphans, []);
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('a voice row speaks the scenario line, not the storyboard blockquote', async () => {
    const root = mkdtempSync(join(tmpdir(), 'is-ws-'));
    try {
      const dir = join(root, 'demo');
      mkdirSync(dir, { recursive: true });

      // One blockquote, three sentences: how a person writes a delivery. The
      // scenario splits the same words across two displayed lines, so the two
      // documents do not line up by position.
      writeFileSync(
        join(dir, 'demo-storyboard.md'),
        [
          '### Shot A.1 — Open',
          '**Hold:** 5 s · **Scene:** `room`',
          '',
          '**VO — `narr`**',
          '> First sentence. Second sentence.',
          '> Third sentence.',
          '',
          '*Delivery: unhurried, no menace.*',
          '',
        ].join('\n'),
        'utf8',
      );

      writeFileSync(
        join(dir, 'scenario.yaml'),
        [
          'id: x',
          'title: X',
          'start: a1_open',
          'characters: { narr: { name: Narr } }',
          'scenes: { room: {} }',
          'nodes:',
          '  - id: a1_open',
          '    type: dialogue',
          '    scene: room',
          '    lines:',
          '      - { who: narr, text: First sentence. Second sentence., ' +
            'voice: narr-a1-01.mp3, hold: 4 }',
          '      - { who: narr, text: Third sentence., voice: narr-a1-02.mp3, hold: 3 }',
          '    next: z',
          '  - { id: z, type: end }',
          '',
        ].join('\n'),
        'utf8',
      );
      writeFileSync(
        join(dir, 'project.yaml'),
        [
          'project: demo',
          'scenario: scenario.yaml',
          'publish: assets',
          'storyboard: demo-storyboard.md',
          '',
        ].join('\n'),
        'utf8',
      );

      process.env.EDITOR_CONFIG_DIR = join(root, '.config');
      const { setWorkspace } = await import('../tools/editor/workspace.ts');
      const { syncFromStoryboard, openProject } = await import('../tools/editor/projects.ts');
      await setWorkspace(root);

      await syncFromStoryboard('demo');
      const opened = await openProject('demo');
      const assets = opened.project.assets;

      // Both clips exist, and the second one says its own words. Indexing the
      // storyboard by line number would have left it empty or, worse, given it
      // the first line's text.
      assert.equal(assets['narr-a1-01.mp3']?.text, 'First sentence. Second sentence.');
      assert.equal(assets['narr-a1-02.mp3']?.text, 'Third sentence.');

      // A shot names its delivery once; every line split out of that block
      // wants the same note.
      assert.equal(assets['narr-a1-01.mp3']?.prompt, 'unhurried, no menace.');
      assert.equal(assets['narr-a1-02.mp3']?.prompt, 'unhurried, no menace.');
      assert.equal(assets['narr-a1-02.mp3']?.source?.line, 1);
      assert.equal(assets['narr-a1-02.mp3']?.source?.node, 'a1_open');
    } finally {
      delete process.env.EDITOR_CONFIG_DIR;
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('wiring voice onto a scenario', () => {
  const SOURCE = [
    '# Why this show is paced the way it is.',
    'id: x',
    'title: X',
    'start: a1_jetty',
    'characters: { narr: { name: Narr }, tran: { name: Tran } }',
    'scenes: { halifax: {} }',
    'nodes:',
    '  # The cold open. Two lines, because one would not breathe.',
    '  - id: a1_jetty',
    '    type: dialogue',
    '    scene: halifax',
    '    lines:',
    '      - who: narr',
    '        text: >-',
    '          Zero four hundred, Halifax. The pier is busy the way it always',
    '          is before a ship sails.',
    '      - who: narr',
    '        text: Fuel lines. Weather brief.',
    '        hold: 5',
    '      - { who: tran, text: Link is good. }',
    '    next: z',
    '  - { id: z, type: end }',
    '',
  ].join('\n');

  const shots = parseStoryboard(
    ['### Shot A.1 — Cold open', '**Hold:** 8 s · **Scene:** `halifax`', ''].join('\n'),
  ).shots;

  function wire(source: string) {
    const parsed = parseScenarioSource(source);
    assert.ok(parsed.ok, parsed.ok ? '' : parsed.message);
    return wireVoiceInto(source, parsed.scenario, shots);
  }

  test('every spoken line gets a clip and the hold a clip requires', () => {
    const result = wire(SOURCE);
    assert.deepEqual(
      result.wired.map((w) => w.file),
      ['voice/narr-a1-01.mp3', 'voice/narr-a1-02.mp3', 'voice/tran-a1-01.mp3'],
    );

    // Nothing on the server opens the audio file, so a voiced line without a
    // hold is a narrator cut off mid-sentence in front of a room.
    const parsed = parseScenarioSource(result.source);
    assert.ok(parsed.ok, parsed.ok ? '' : parsed.message);
    const node = parsed.scenario.nodes[0]!;
    assert.equal(node.type, 'dialogue');
    if (node.type !== 'dialogue') return;
    for (const line of node.lines) {
      assert.ok(line.voice, 'every line has a clip');
      assert.ok(line.hold !== undefined, `${line.voice} has a hold`);
    }
    // The line that already declared its own hold keeps it.
    assert.equal(node.lines[1]!.hold, 5);
  });

  test('the author s file is only ever inserted into', () => {
    const result = wire(SOURCE);
    const before = SOURCE.split('\n');
    const after = result.source.split('\n');

    // Every original line survives in order, comments and hand-wrapped folded
    // scalars included. Re-serialising the document would reflow all of them
    // and bury the change under rewrapped prose.
    // The inline line is the one exception: a flow map is extended in place,
    // which is checked separately below.
    let cursor = 0;
    for (const line of before.filter((l) => !l.includes('{ who: tran'))) {
      const found = after.indexOf(line, cursor);
      assert.notEqual(found, -1, `lost line: ${JSON.stringify(line)}`);
      cursor = found + 1;
    }
    assert.match(result.source, /# The cold open\./);
    assert.match(result.source, /# Why this show is paced/);
    // Two new keys on the first line, one on the second, and none on the
    // inline third, which grew sideways.
    assert.equal(after.length, before.length + 3);
  });

  test('a line written inline stays inline', () => {
    // `{ who: tran, text: … }` is how a short line is often written, and a
    // newline inserted into a flow map is not YAML at all.
    assert.match(
      wire(SOURCE).source,
      /\{ who: tran, text: Link is good\., hold: \d+, voice: voice\/tran-a1-01\.mp3 \}/,
    );
  });

  test('pressing it twice changes nothing the second time', () => {
    const once = wire(SOURCE);
    const twice = wire(once.source);
    assert.deepEqual(twice.wired, []);
    assert.equal(twice.untouched, 3);
    assert.equal(twice.source, once.source);
  });

  test('numbering continues from what the scenario already uses', () => {
    // A half-wired scenario is the normal case: a line gets added to a node
    // that was wired last week. Restarting at 01 would collide with a clip
    // that already exists on disk.
    const partial = SOURCE.replace(
      '      - who: narr\n        text: Fuel lines. Weather brief.\n        hold: 5',
      '      - who: narr\n        text: Fuel lines. Weather brief.\n        hold: 5\n        voice: narr-a1-07.mp3',
    );
    const result = wire(partial);
    // The existing clip is flat and the new ones are filed, which is the state
    // any scenario written before folders existed is in. Numbering is read by
    // basename so the two spellings still count as the same run of takes —
    // restarting at 01 would name a file that is already on disk.
    assert.deepEqual(
      result.wired.map((w) => w.file),
      ['voice/narr-a1-08.mp3', 'voice/tran-a1-01.mp3'],
    );
  });

  test('a node the storyboard never numbered falls back to its own id', () => {
    const orphaned = SOURCE.replace(/a1_jetty/g, 'p1_defend');
    assert.equal(wire(orphaned).wired[0]!.file, 'voice/narr-p1-defend-01.mp3');
  });
});

/**
 * A line nobody is credited with still has to be spoken.
 *
 * The fiction notice that opens a show, a title card, a line the display shows
 * without a nameplate: real work, and the only beat in a finished show that
 * would come out silent, because nothing upstream had a voice to give it.
 */
describe('the voice of a line with no nameplate', () => {
  const uncredited = ScenarioSchema.parse({
    id: 'x',
    title: 'X',
    start: 'a',
    characters: { narr: { name: 'Narrator' } },
    scenes: {},
    nodes: [
      {
        id: 'a',
        type: 'dialogue',
        lines: [
          { text: 'Every ship, unit, person and system in what follows is invented.', hold: 6 },
          {
            text: 'Nothing here depicts real capability, doctrine, or rules of engagement.',
            hold: 7,
          },
          { who: 'narr', text: 'Zero four hundred, Halifax.', hold: 3 },
        ],
        next: 'z',
      },
      { id: 'z', type: 'end', text: 'Done' },
    ],
  });

  test('wiring names its clips for the narration voice, not for a character', () => {
    const result = wireVoiceInto(
      [
        'id: x',
        'title: X',
        'start: a',
        'characters: { narr: { name: Narrator } }',
        'scenes: {}',
        'nodes:',
        '  - id: a',
        '    type: dialogue',
        '    lines:',
        '      - { text: Every ship in what follows is invented. }',
        '      - { who: narr, text: Zero four hundred. }',
        '    next: z',
        '  - { id: z, type: end }',
        '',
      ].join('\n'),
      ScenarioSchema.parse({
        id: 'x',
        title: 'X',
        start: 'a',
        characters: { narr: { name: 'Narrator' } },
        scenes: {},
        nodes: [
          {
            id: 'a',
            type: 'dialogue',
            lines: [
              { text: 'Every ship in what follows is invented.' },
              { who: 'narr', text: 'Zero four hundred.' },
            ],
            next: 'z',
          },
          { id: 'z', type: 'end', text: 'Done' },
        ],
      }),
      [],
    );
    // `vo`, not `narr`: attributing it to the narrator to get a voice would put
    // that character's name on screen under a legal disclaimer.
    assert.deepEqual(
      result.wired.map((w) => w.file),
      ['voice/vo-a-01.mp3', 'voice/narr-a-01.mp3'],
    );
  });

  test('seeding gives the row a voice, so it can actually be generated', () => {
    const withClips = ScenarioSchema.parse({
      id: 'x',
      title: 'X',
      start: 'a',
      characters: { narr: { name: 'Narrator' } },
      scenes: {},
      nodes: [
        {
          id: 'a',
          type: 'dialogue',
          lines: [
            { text: 'Invented.', hold: 6, voice: 'voice/vo-a-01.mp3' },
            { who: 'narr', text: 'Zero four hundred.', hold: 3, voice: 'voice/narr-a-01.mp3' },
          ],
          next: 'z',
        },
        { id: 'z', type: 'end', text: 'Done' },
      ],
    });

    const rows = seedRowsFor(withClips, []).rows;
    const uncreditedRow = rows.find((row) => row.file === 'voice/vo-a-01.mp3');
    assert.equal(uncreditedRow?.voice, 'vo', 'a row with no voice refuses to generate');
    assert.equal(rows.find((row) => row.file === 'voice/narr-a-01.mp3')?.voice, 'narr');
  });

  test('a reference clip for it is read from the lines nobody is credited with', async () => {
    const { referenceTextFor } = await import('../tools/editor/generate.ts');
    const text = referenceTextFor(uncredited, 'vo')!;
    assert.match(text, /^Every ship, unit, person/);
    // Matching by name would find nothing at all, and refuse to record a clip
    // for a voice that plainly has work to do.
    assert.ok(!text.includes('Zero four hundred'), 'took a credited line');
    assert.match(referenceTextFor(uncredited, 'narr')!, /Zero four hundred/);
  });

  test('it appears in the cast under a name that says what it is', async () => {
    const { buildOverview } = await import('../tools/editor/sections.ts');
    const { ProjectSchema, pathsOf, EMPTY_LEDGER } = await import('../tools/editor/project.ts');
    const withClips = ScenarioSchema.parse({
      id: 'x',
      title: 'X',
      start: 'a',
      characters: { narr: { name: 'Narrator' } },
      scenes: {},
      nodes: [
        {
          id: 'a',
          type: 'dialogue',
          lines: [{ text: 'Invented.', hold: 6, voice: 'voice/vo-a-01.mp3' }],
          next: 'z',
        },
        { id: 'z', type: 'end', text: 'Done' },
      ],
    });
    const proj = ProjectSchema.parse({
      project: 'x',
      scenario: 'scenario.yaml',
      publish: 'assets',
      assets: { 'voice/vo-a-01.mp3': { text: 'Invented.', voice: 'vo' } },
    });

    const overview = await buildOverview(
      withClips,
      proj,
      structuredClone(EMPTY_LEDGER),
      pathsOf(join(tmpdir(), 'nowhere', 'project.yaml'), proj),
    );
    const member = overview.cast.find((entry) => entry.id === 'vo');
    assert.equal(member?.name, 'Narration — no nameplate');
    assert.equal(member?.lines, 1);
    // Uncast, which is the state the panel exists to make impossible to miss.
    assert.equal(member?.reference, undefined);
  });
});

describe('the editor cannot reach the live server', () => {
  /**
   * The editor used to serve `/api/scenarios`, including a PUT that wrote
   * straight into the repo's `scenarios/` folder — the one the game server
   * reads, possibly mid-show. Authoring and running are weeks apart and must
   * not share a filesystem path.
   *
   * Read as a file rather than started as a server, because the point is that
   * the capability is absent from the source, not merely unreachable today.
   */
  const source = readFileSync(join(import.meta.dirname, '..', 'tools', 'editor', 'server.ts'), 'utf8');

  test('serves no route into the scenarios folder', () => {
    assert.doesNotMatch(source, /['"`]\/api\/scenarios/);
    assert.doesNotMatch(source, /SCENARIOS_DIR/);
  });

  test('never writes a file outside the workspace', () => {
    // Every write the editor performs goes through projects.ts, which resolves
    // paths under the chosen workspace and refuses anything outside it.
    assert.doesNotMatch(source, /\bwriteFile\b/);
    assert.doesNotMatch(source, /\brename\b/);
  });
});

describe('a shot that carries its own still', () => {
  test('takes its prompt from its own shot, not the establishing one', () => {
    // The case the schema change exists for: two shots in one place. Before a
    // node could carry its own still, the second shot had nowhere to attach and
    // was reported unmatched — most of a storyboard's visual work.
    const board = [
      '### Shot A.1 — The jetty',
      '**Hold:** 8 s · **Scene:** `halifax`',
      '',
      '**IMAGE**',
      '```',
      'wide establishing shot of the pier',
      '```',
      '',
      '### Shot A.2 — The absence',
      '**Hold:** 7 s · **Scene:** `halifax`',
      '',
      '**IMAGE**',
      '```',
      'tight along the hull, no gangway',
      '```',
      '**MOTION** the amber light pulses once per 2 s',
      '',
    ].join('\n');

    const scenario = parseScenarioSource(
      [
        'id: x',
        'title: X',
        'start: a1_jetty',
        'scenes: { halifax: { background: a1-jetty.jpg } }',
        'nodes:',
        '  - id: a1_jetty',
        '    type: dialogue',
        '    scene: halifax',
        '    lines: [{ text: One., hold: 3 }]',
        '    next: a2_absence',
        '  - id: a2_absence',
        '    type: dialogue',
        '    background: a2-flank.jpg',
        '    video: a2-flank.mp4',
        '    lines: [{ text: Two., hold: 3 }]',
        '    next: z',
        '  - { id: z, type: end }',
        '',
      ].join('\n'),
    );
    assert.ok(scenario.ok, scenario.ok ? '' : scenario.message);

    const { rows, unmatched } = seedRowsFor(scenario.scenario, parseStoryboard(board).shots);
    const row = (file: string) => rows.find((r) => r.file === file);

    assert.equal(row('a1-jetty.jpg')?.prompt, 'wide establishing shot of the pier');
    assert.equal(row('a2-flank.jpg')?.prompt, 'tight along the hull, no gangway');
    assert.equal(row('a2-flank.mp4')?.prompt, 'the amber light pulses once per 2 s');
    assert.equal(row('a2-flank.jpg')?.source.node, 'a2_absence');
    assert.deepEqual(unmatched, []);
  });
});
